In [1]:
import numpy as np
import pandas as pd 
provincial = pd.read_csv('Provincial_Daily_Totals.csv')
provincial.head()

,OBJECTID,Province,Abbreviation,DailyTotals,SummaryDate,TotalCases,TotalRecovered,DailyRecovered,TotalDeaths,DailyDeaths,TotalTested,DailyTested,TotalActive,DailyActive,TotalHospitalized,DailyHospitalized,TotalICU,DailyICU,TotalVaccinated,DailyVaccinated
0,1,ALBERTA,AB,0,2020/01/25 12:00:00+00,0,0,0,0,0,0,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2,NWT,NT,0,2020/01/25 12:00:00+00,0,0,0,0,0,0,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,3,YUKON,YT,0,2020/01/25 12:00:00+00,0,0,0,0,0,0,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,4,SASKATCHEWAN,SK,0,2020/01/25 12:00:00+00,0,0,0,0,0,0,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,5,PEI,PE,0,2020/01/25 12:00:00+00,0,0,0,0,0,0,0,0,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
provincial['Province'].value_counts()

SASKATCHEWAN                 495
CANADA                       495
ONTARIO                      495
MANITOBA                     495
QUEBEC                       495
ALBERTA                      495
YUKON                        495
NEW BRUNSWICK                495
NOVA SCOTIA                  495
NUNAVUT                      495
BRITISH COLUMBIA             420
NORTHWEST TERRITORIES        420
REPATRIATED CDN              420
PRINCE EDWARD ISLAND         420
NEWFOUNDLAND AND LABRADOR    420
NWT                           75
NL                            75
PEI                           75
REPATRIATED                   75
BC                            75
Name: Province, dtype: int64

In [3]:
provincial.describe()

,OBJECTID,DailyTotals,TotalCases,TotalRecovered,DailyRecovered,TotalDeaths,DailyDeaths,TotalTested,DailyTested,TotalActive,DailyActive,TotalHospitalized,DailyHospitalized,TotalICU,DailyICU,TotalVaccinated,DailyVaccinated
count,7425.000000,7425.000000,7.425000e+03,7.425000e+03,7425.000000,7425.000000,7425.000000,7.425000e+03,7.425000e+03,7425.000000,7417.000000,6300.000000,6300.000000,6300.000000,6300.000000,2.238000e+03,2.238000e+03
mean,4002.500202,373.137104,5.320676e+04,4.720084e+04,358.213333,1540.944646,6.894545,1.570031e+06,9.597212e+03,4441.273805,7.978563,278.399206,0.647302,66.946984,0.296032,9.413879e+05,2.690524e+04
std,2364.959943,1106.092053,1.606486e+05,1.474462e+05,1159.963947,3967.914838,21.691293,4.535693e+06,6.646964e+04,11685.928880,528.806757,669.459352,42.171514,178.612116,14.846609,2.744345e+06,1.349564e+05
min,1.000000,-148.000000,0.000000e+00,0.000000e+00,-2115.000000,0.000000,-6.000000,0.000000e+00,-1.947669e+06,-2.000000,-23702.000000,0.000000,-519.000000,0.000000,-238.000000,0.000000e+00,-4.365510e+05
25%,1973.000000,0.000000,1.500000e+01,1.300000e+01,0.000000,0.000000,0.000000,2.953000e+03,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.727700e+04,0.000000e+00
50%,3934.000000,1.000000,3.950000e+02,3.370000e+02,1.000000,6.000000,0.000000,6.556800e+04,3.190000e+02,27.000000,0.000000,3.000000,0.000000,1.000000,0.000000,6.985100e+04,1.515000e+03
75%,6015.000000,158.000000,2.595700e+04,1.834900e+04,126.000000,447.000000,2.000000,5.946090e+05,4.072000e+03,2322.000000,4.000000,216.000000,0.000000,41.000000,0.000000,4.722112e+05,1.206775e+04
max,8156.000000,13670.000000,1.385278e+06,1.330389e+06,24009.000000,25612.000000,268.000000,3.556053e+07,2.666495e+06,88220.000000,5846.000000,4715.000000,1765.000000,1455.000000,789.000000,2.451413e+07,4.527368e+06

In [4]:
provincial.shape

(7425, 20)

In [2]:
provincial['SummaryDate'].max()

'2021/06/02 12:00:00+00'

In [3]:
provincial['SummaryDate'].min()

'2020/01/25 12:00:00+00'

In [7]:
provincial.isnull().sum()

OBJECTID                0
Province                0
Abbreviation            0
DailyTotals             0
SummaryDate             0
TotalCases              0
TotalRecovered          0
DailyRecovered          0
TotalDeaths             0
DailyDeaths             0
TotalTested             0
DailyTested             0
TotalActive             0
DailyActive             8
TotalHospitalized    1125
DailyHospitalized    1125
TotalICU             1125
DailyICU             1125
TotalVaccinated      5187
DailyVaccinated      5187
dtype: int64

In [8]:
#drop columns not in need
provincial.drop(['TotalHospitalized'], axis=1, inplace=True)
provincial.drop(['DailyHospitalized'], axis=1, inplace=True)
provincial.drop(['TotalICU'], axis=1, inplace=True)
provincial.drop(['DailyICU'], axis=1, inplace=True)
provincial.drop(['TotalTested'], axis=1, inplace=True)
provincial.drop(['DailyTested'], axis=1, inplace=True)
provincial.drop(['OBJECTID'], axis=1, inplace=True)

In [9]:
provincial

,Province,Abbreviation,DailyTotals,SummaryDate,TotalCases,TotalRecovered,DailyRecovered,TotalDeaths,DailyDeaths,TotalActive,DailyActive,TotalVaccinated,DailyVaccinated
0,ALBERTA,AB,0,2020/01/25 12:00:00+00,0,0,0,0,0,0,0.0,NaN,NaN
1,NWT,NT,0,2020/01/25 12:00:00+00,0,0,0,0,0,0,0.0,NaN,NaN
2,YUKON,YT,0,2020/01/25 12:00:00+00,0,0,0,0,0,0,0.0,NaN,NaN
3,SASKATCHEWAN,SK,0,2020/01/25 12:00:00+00,0,0,0,0,0,0,0.0,NaN,NaN
4,PEI,PE,0,2020/01/25 12:00:00+00,0,0,0,0,0,0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7420,QUEBEC,QC,288,2021/06/02 12:00:00+00,370815,356202,417,11138,5,3475,-134.0,5719839.0,136764.0
7421,ONTARIO,ON,733,2021/06/02 12:00:00+00,532891,513436,1733,8791,25,10664,-1025.0,9342121.0,139901.0
7422,NORTHWEST TERRITORIES,NT,0,2021/06/02 12:00:00+00,128,128,0,0,0,0,0.0,53501.0,0.0
7423,REPATRIATED CDN,RC,0,2021/06/02 12:00:00+00,13,13,0,0,0,0,0.0,0.0,0.0
7424,CANADA,CA,2064,2021/06/02 12:00:00+00,1385278,1330389,3905,25612,46,29212,-1876.0,24514134.0,410858.0

#provincial.set_index('OBJECTID')

In [10]:
#Replace all provinces to right ones
provincial['Province'] = provincial['Province'].replace({'ALBERTA':'Alberta', 'YUKON':'Yukon','ONTARIO':'Ontario','SASKATCHEWAN':'Saskatchewan','NOVA SCOTIA':'Nova Scotia','NUNAVUT':'Nunavut', 'MANITOBA':'Manitoba','NEW BRUNSWICK':'New Brunswick','QUEBEC':'Quebec','NORTHWEST TERRITORIES':'NWT','PRINCE EDWARD ISLAND':'PEI','BRITISH COLUMBIA':'BC','REPATRIATED CDN':'Repatriated','REPATRIATED ':'Repatriated','NEWFOUNDLAND AND LABRADOR':'NWL'})

#Drop all the rows with province Canada (That is just a Total numbers)
provincial.drop(provincial.loc[provincial['Province']=='CANADA'].index, inplace=True)

In [11]:
provincial['Province'].value_counts()

NWT              495
Saskatchewan     495
Manitoba         495
Nova Scotia      495
Nunavut          495
PEI              495
BC               495
Yukon            495
Ontario          495
Alberta          495
Quebec           495
New Brunswick    495
Repatriated      420
NWL              420
REPATRIATED       75
NL                75
Name: Province, dtype: int64

In [12]:
Holidays=pd.read_csv('/Users/sahrarahim/Desktop/Springboard/CapstoneProject2/Covid19/Dataset/Covid19Canada/timeseries_prov/Holiday Calendar.csv')

In [13]:
Seasons=pd.read_csv('/Users/sahrarahim/Desktop/Springboard/CapstoneProject2/Covid19/Dataset/Covid19Canada/timeseries_prov/Seasons.csv')

In [14]:
MainEvents=pd.read_csv('/Users/sahrarahim/Desktop/Springboard/CapstoneProject2/Covid19/Dataset/Covid19Canada/timeseries_prov/Main Events.csv')

In [15]:
provincial.head()

,Province,Abbreviation,DailyTotals,SummaryDate,TotalCases,TotalRecovered,DailyRecovered,TotalDeaths,DailyDeaths,TotalActive,DailyActive,TotalVaccinated,DailyVaccinated
0,Alberta,AB,0,2020/01/25 12:00:00+00,0,0,0,0,0,0,0.0,NaN,NaN
1,NWT,NT,0,2020/01/25 12:00:00+00,0,0,0,0,0,0,0.0,NaN,NaN
2,Yukon,YT,0,2020/01/25 12:00:00+00,0,0,0,0,0,0,0.0,NaN,NaN
3,Saskatchewan,SK,0,2020/01/25 12:00:00+00,0,0,0,0,0,0,0.0,NaN,NaN
4,PEI,PE,0,2020/01/25 12:00:00+00,0,0,0,0,0,0,0.0,NaN,NaN

In [16]:
Holidays.head()

        province        date    Holiday name
0        Ontario  01-01-2020  New Year's day
1             BC  01-01-2020  New Year's day
2       Manitoba  01-01-2020  New Year's day
3  New Brunswick  01-01-2020  New Year's day
4             NL  01-01-2020  New Year's day

In [17]:
provincial['SummaryDate'].value_counts()

2020/08/03 12:00:00+00    14
2020/09/16 12:00:00+00    14
2020/12/16 12:00:00+00    14
2020/06/07 12:00:00+00    14
2020/07/16 12:00:00+00    14
                          ..
2021/05/21 12:00:00+00    14
2020/08/26 12:00:00+00    14
2021/02/15 12:00:00+00    14
2020/06/18 12:00:00+00    14
2021/03/30 12:00:00+00    14
Name: SummaryDate, Length: 495, dtype: int64

In [18]:
provincial.loc[provincial['SummaryDate']=='2020-08-02']

Empty DataFrame
Columns: [Province, Abbreviation, DailyTotals, SummaryDate, TotalCases, TotalRecovered, DailyRecovered, TotalDeaths, DailyDeaths, TotalActive, DailyActive, TotalVaccinated, DailyVaccinated]
Index: []

In [19]:
provincial['SummaryDate'].dtype

dtype('O')

In [20]:
provincial['SummaryDate']=pd.to_datetime(provincial['SummaryDate']).dt.tz_localize(None)

In [21]:
provincial['SummaryDate']=pd.to_datetime(provincial['SummaryDate'],format='%Y-%m-%d %H:%M:%S')

In [22]:
provincial

,Province,Abbreviation,DailyTotals,SummaryDate,TotalCases,TotalRecovered,DailyRecovered,TotalDeaths,DailyDeaths,TotalActive,DailyActive,TotalVaccinated,DailyVaccinated
0,Alberta,AB,0,2020-01-25 12:00:00,0,0,0,0,0,0,0.0,NaN,NaN
1,NWT,NT,0,2020-01-25 12:00:00,0,0,0,0,0,0,0.0,NaN,NaN
2,Yukon,YT,0,2020-01-25 12:00:00,0,0,0,0,0,0,0.0,NaN,NaN
3,Saskatchewan,SK,0,2020-01-25 12:00:00,0,0,0,0,0,0,0.0,NaN,NaN
4,PEI,PE,0,2020-01-25 12:00:00,0,0,0,0,0,0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7419,Manitoba,MB,264,2021-06-02 12:00:00,51580,46251,324,1062,6,4267,-66.0,874564.0,12019.0
7420,Quebec,QC,288,2021-06-02 12:00:00,370815,356202,417,11138,5,3475,-134.0,5719839.0,136764.0
7421,Ontario,ON,733,2021-06-02 12:00:00,532891,513436,1733,8791,25,10664,-1025.0,9342121.0,139901.0
7422,NWT,NT,0,2021-06-02 12:00:00,128,128,0,0,0,0,0.0,53501.0,0.0
7423,Repatriated,RC,0,2021-06-02 12:00:00,13,13,0,0,0,0,0.0,0.0,0.0

In [23]:
provincial['SummaryDate']=provincial['SummaryDate'].apply(lambda x: str(x).split(' ')[0])

In [24]:
provincial

,Province,Abbreviation,DailyTotals,SummaryDate,TotalCases,TotalRecovered,DailyRecovered,TotalDeaths,DailyDeaths,TotalActive,DailyActive,TotalVaccinated,DailyVaccinated
0,Alberta,AB,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN
1,NWT,NT,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN
2,Yukon,YT,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN
3,Saskatchewan,SK,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN
4,PEI,PE,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7419,Manitoba,MB,264,2021-06-02,51580,46251,324,1062,6,4267,-66.0,874564.0,12019.0
7420,Quebec,QC,288,2021-06-02,370815,356202,417,11138,5,3475,-134.0,5719839.0,136764.0
7421,Ontario,ON,733,2021-06-02,532891,513436,1733,8791,25,10664,-1025.0,9342121.0,139901.0
7422,NWT,NT,0,2021-06-02,128,128,0,0,0,0,0.0,53501.0,0.0
7423,Repatriated,RC,0,2021-06-02,13,13,0,0,0,0,0.0,0.0,0.0

A=provincial

A['year']=A['date'].apply(lambda x: str(x).split('-')[0])

A['Month']=A['date'].apply(lambda x: str(x).split('-')[1])

A['Date']=A['date'].apply(lambda x: str(x).split('-')[2])

A['new_date']=A.apply(lambda row: row['year']+'-'+row['Month']+'-'+row['Date'], axis=1)

In [25]:
Holidays['date'].value_counts().count()

35

In [26]:
Holidays['date'].nunique()

35

In [27]:
Holidays['date'].dtype

dtype('O')

In [28]:
Holidays['date']=pd.to_datetime(Holidays['date'])

In [29]:
provincial=provincial.rename(columns = {'SummaryDate':'date'})
provincial=provincial.rename(columns = {'Province':'province'})

In [30]:
Holidays['date'].dtype

dtype('<M8[ns]')

In [31]:
provincial['date'].dtype

dtype('O')

In [32]:
provincial['date']=pd.to_datetime(provincial['date'])

In [33]:
provincial.shape

(6930, 13)

In [34]:
Pro_Holidays=provincial.merge(Holidays,how='left',on=['date','province'])

In [35]:
Pro_Holidays.head(30)

,province,Abbreviation,DailyTotals,date,TotalCases,TotalRecovered,DailyRecovered,TotalDeaths,DailyDeaths,TotalActive,DailyActive,TotalVaccinated,DailyVaccinated,Holiday name
0,Alberta,AB,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN,NaN
1,NWT,NT,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN,NaN
2,Yukon,YT,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN,NaN
3,Saskatchewan,SK,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN,NaN
4,PEI,PE,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN,NaN
5,Ontario,ON,1,2020-01-25,1,0,0,0,0,1,1.0,NaN,NaN,NaN
6,New Brunswick,NB,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN,NaN
7,REPATRIATED,RC,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN,NaN
8,Nova Scotia,NS,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN,NaN
9,NL,NL,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN,NaN
10,Manitoba,MB,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN,NaN
11,BC,BC,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN,NaN
12,Nunavut,NU,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN,NaN
13,Quebec,QC,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN,NaN
14,PEI,PE,0,2020-01-26,0,0,0,0,0,0,0.0,NaN,NaN,NaN
15,NWT,NT,0,2020-01-26,0,0,0,0,0,0,0.0,NaN,NaN,NaN
16,Ontario,ON,0,2020-01-26,1,0,0,0,0,1,0.0,NaN,NaN,NaN
17,Yukon,YT,0,2020-01-26,0,0,0,0,0,0,0.0,NaN,NaN,NaN
18,Saskatchewan,SK,0,2020-01-26,0,0,0,0,0,0,0.0,NaN,NaN,NaN
19,Quebec,QC,0,2020-01-26,0,0,0,0,0,0,0.0,NaN,NaN,NaN
20,REPATRIATED,RC,0,2020-01-26,0,0,0,0,0,0,0.0,NaN,NaN,NaN
21,BC,BC,0,2020-01-26,0,0,0,0,0,0,0.0,NaN,NaN,NaN
22,NL,NL,0,2020-01-26,0,0,0,0,0,0,0.0,NaN,NaN,NaN
23,Manitoba,MB,0,2020-01-26,0,0,0,0,0,0,0.0,NaN,NaN,NaN
24,Alberta,AB,0,2020-01-26,0,0,0,0,0,0,0.0,NaN,NaN,NaN
25,Nunavut,NU,0,2020-01-26,0,0,0,0,0,0,0.0,NaN,NaN,NaN
26,Nova Scotia,NS,0,2020-01-26,0,0,0,0,0,0,0.0,NaN,NaN,NaN
27,New Brunswick,NB,0,2020-01-26,0,0,0,0,0,0,0.0,NaN,NaN,NaN
28,PEI,PE,0,2020-01-27,0,0,0,0,0,0,0.0,NaN,NaN,NaN
29,NWT,NT,0,2020-01-27,0,0,0,0,0,0,0.0,NaN,NaN,NaN

In [36]:
Pro_Holidays=Pro_Holidays.rename(columns = {'Holiday name':'Holiday?'})

In [37]:
Pro_Holidays

,province,Abbreviation,DailyTotals,date,TotalCases,TotalRecovered,DailyRecovered,TotalDeaths,DailyDeaths,TotalActive,DailyActive,TotalVaccinated,DailyVaccinated,Holiday?
0,Alberta,AB,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN,NaN
1,NWT,NT,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN,NaN
2,Yukon,YT,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN,NaN
3,Saskatchewan,SK,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN,NaN
4,PEI,PE,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6926,Manitoba,MB,264,2021-06-02,51580,46251,324,1062,6,4267,-66.0,874564.0,12019.0,NaN
6927,Quebec,QC,288,2021-06-02,370815,356202,417,11138,5,3475,-134.0,5719839.0,136764.0,NaN
6928,Ontario,ON,733,2021-06-02,532891,513436,1733,8791,25,10664,-1025.0,9342121.0,139901.0,NaN
6929,NWT,NT,0,2021-06-02,128,128,0,0,0,0,0.0,53501.0,0.0,NaN
6930,Repatriated,RC,0,2021-06-02,13,13,0,0,0,0,0.0,0.0,0.0,NaN

In [38]:
Holidays.head()

        province       date    Holiday name
0        Ontario 2020-01-01  New Year's day
1             BC 2020-01-01  New Year's day
2       Manitoba 2020-01-01  New Year's day
3  New Brunswick 2020-01-01  New Year's day
4             NL 2020-01-01  New Year's day

In [39]:
Holidays['Holiday name'].nunique()

21

In [40]:
Pro_Holidays['Holiday?'].nunique()

21

In [41]:
Pro_Holidays['Holiday?'].value_counts()

Valentine's day          25
St. Patricks Day         25
Easter                   24
Victoria Day             20
Halloween                12
Civic Holiday            12
Labours Day              12
Mothers Day              12
Fathers Day              12
New Year's day           12
Boxing Day               12
Canada Day               12
Christmas                12
Family Day               10
Thanksgiving             10
Remembrance Day           8
Louis Riel Day            2
Islander Day              2
Heritage Day              2
St. Jean Baptiste Day     1
Aboriginal Day            1
Name: Holiday?, dtype: int64

In [42]:
Holidays.shape

(376, 3)

In [43]:
Pro_Holidays.shape

(6931, 14)

In [44]:
MainEvents.head()

  province        date                Holiday name
0  Ontario  07-01-2020  Raised Awarness on Airport
1       BC  07-01-2020  Raised Awarness on Airport
2   Quebec  07-01-2020  Raised Awarness on Airport
3  Ontario  11-03-2020  COVID 19 Pandemic declared
4       BC  11-03-2020  COVID 19 Pandemic declared

In [45]:
MainEvents['date'].dtype

dtype('O')

In [46]:
MainEvents['date']=pd.to_datetime(MainEvents['date'])

In [47]:
Data=Pro_Holidays.merge(MainEvents,how='left',on=['date','province'])

In [48]:
Data.head()

,province,Abbreviation,DailyTotals,date,TotalCases,TotalRecovered,DailyRecovered,TotalDeaths,DailyDeaths,TotalActive,DailyActive,TotalVaccinated,DailyVaccinated,Holiday?,Holiday name
0,Alberta,AB,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN,NaN,NaN
1,NWT,NT,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN,NaN,NaN
2,Yukon,YT,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN,NaN,NaN
3,Saskatchewan,SK,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN,NaN,NaN
4,PEI,PE,0,2020-01-25,0,0,0,0,0,0,0.0,NaN,NaN,NaN,NaN

In [49]:
Data.isnull().sum()

province              0
Abbreviation          0
DailyTotals           0
date                  0
TotalCases            0
TotalRecovered        0
DailyRecovered        0
TotalDeaths           0
DailyDeaths           0
TotalActive           0
DailyActive           8
TotalVaccinated    4844
DailyVaccinated    4844
Holiday?           6695
Holiday name       6854
dtype: int64

In [50]:
a=Data.copy()

In [51]:
a['Holiday?'].replace('No',np.NaN,inplace=True)

In [52]:
a.loc[~a['Holiday?'].isnull() & ~a['Holiday name'].isnull()]

,province,Abbreviation,DailyTotals,date,TotalCases,TotalRecovered,DailyRecovered,TotalDeaths,DailyDeaths,TotalActive,DailyActive,TotalVaccinated,DailyVaccinated,Holiday?,Holiday name
728,PEI,PE,0,2020-03-17,1,0,0,0,0,1,0.0,NaN,NaN,St. Patricks Day,Lockdown Started
741,Nunavut,NU,0,2020-03-17,0,0,0,0,0,0,0.0,NaN,NaN,St. Patricks Day,Lockdown Started

In [53]:
Data['TotalVaccinated']=Data['TotalVaccinated'].replace(np.nan,0,inplace=True)

In [54]:
Data.replace(np.nan,'No',inplace=True)

In [55]:
Data.isnull().sum()

province           0
Abbreviation       0
DailyTotals        0
date               0
TotalCases         0
TotalRecovered     0
DailyRecovered     0
TotalDeaths        0
DailyDeaths        0
TotalActive        0
DailyActive        0
TotalVaccinated    0
DailyVaccinated    0
Holiday?           0
Holiday name       0
dtype: int64

In [56]:
Data["Holiday?"].nunique()

22

In [57]:
Data['Holiday?'].unique()

array(['No', "Valentine's day", 'Family Day', 'Islander Day',
       'Heritage Day', 'Louis Riel Day', 'Civic Holiday',
       'St. Patricks Day', 'Victoria Day', 'Fathers Day',
       'Aboriginal Day', 'St. Jean Baptiste Day', 'Labours Day', 'Easter',
       'Mothers Day', 'Halloween', 'Remembrance Day', 'Thanksgiving',
       'Christmas', 'Boxing Day', "New Year's day", 'Canada Day'],
      dtype=object)

In [58]:
Data['Holiday name'].unique()

array(['No', 'Lockdown Ended', 'Lockdown Started', 'US border Closed',
       'Social Distancing + Mask Mandatory', 'Raised Awarness on Airport',
       'COVID 19 Pandemic declared'], dtype=object)

In [59]:
encoded_columns = pd.get_dummies(Data['Holiday?'])
Data = Data.join(encoded_columns).drop('Holiday?',axis=1)

In [60]:
Data.head()

,province,Abbreviation,DailyTotals,date,TotalCases,TotalRecovered,DailyRecovered,TotalDeaths,DailyDeaths,TotalActive,...,Louis Riel Day,Mothers Day,New Year's day,No,Remembrance Day,St. Jean Baptiste Day,St. Patricks Day,Thanksgiving,Valentine's day,Victoria Day
0,Alberta,AB,0,2020-01-25,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,NWT,NT,0,2020-01-25,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,Yukon,YT,0,2020-01-25,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,Saskatchewan,SK,0,2020-01-25,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,PEI,PE,0,2020-01-25,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [61]:
Data=Data.drop('No',axis=1)

In [62]:
Data.head()

,province,Abbreviation,DailyTotals,date,TotalCases,TotalRecovered,DailyRecovered,TotalDeaths,DailyDeaths,TotalActive,...,Labours Day,Louis Riel Day,Mothers Day,New Year's day,Remembrance Day,St. Jean Baptiste Day,St. Patricks Day,Thanksgiving,Valentine's day,Victoria Day
0,Alberta,AB,0,2020-01-25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,NWT,NT,0,2020-01-25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Yukon,YT,0,2020-01-25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Saskatchewan,SK,0,2020-01-25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,PEI,PE,0,2020-01-25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [63]:
MainEvents.head()

  province       date                Holiday name
0  Ontario 2020-07-01  Raised Awarness on Airport
1       BC 2020-07-01  Raised Awarness on Airport
2   Quebec 2020-07-01  Raised Awarness on Airport
3  Ontario 2020-11-03  COVID 19 Pandemic declared
4       BC 2020-11-03  COVID 19 Pandemic declared

In [64]:
MainEvents.loc[MainEvents['Holiday name']=='Lockdown Started']

         province       date      Holiday name
42        Ontario 2020-03-31  Lockdown Started
44        Ontario 2020-10-10  Lockdown Started
46        Ontario 2021-03-04  Lockdown Started
47             BC 2020-03-20  Lockdown Started
49             BC 2020-07-11  Lockdown Started
51             BC 2021-03-31  Lockdown Started
52       Manitoba 2020-01-04  Lockdown Started
54       Manitoba 2020-10-30  Lockdown Started
56  New Brunswick 2020-03-19  Lockdown Started
58  New Brunswick 2020-11-24  Lockdown Started
60  New Brunswick 2021-03-19  Lockdown Started
61             NL 2020-03-23  Lockdown Started
63             NL 2021-12-02  Lockdown Started
65    Nova Scotia 2020-03-23  Lockdown Started
67    Nova Scotia 2020-11-26  Lockdown Started
69    Nova Scotia 2021-04-28  Lockdown Started
70        Nunavut 2020-03-17  Lockdown Started
72        Nunavut 2020-06-11  Lockdown Started
74        Nunavut 2021-04-15  Lockdown Started
75            NWT 2020-03-16  Lockdown Started
77            PEI 2020-03-17  Lockdown Started
79            PEI 2020-07-12  Lockdown Started
81         Quebec 2020-03-16  Lockdown Started
83         Quebec 2020-01-10  Lockdown Started
85        Alberta 2020-03-27  Lockdown Started
87        Alberta 2020-11-27  Lockdown Started
89        Alberta 2021-09-04  Lockdown Started
90   Saskatchewan 2020-03-18  Lockdown Started
92          Yukon 2020-03-18  Lockdown Started

In [65]:
MainEvents.loc[MainEvents['Holiday name']=='Lockdown started']

Empty DataFrame
Columns: [province, date, Holiday name]
Index: []

In [66]:
MainEvents.loc[(MainEvents['Holiday name']=='Lockdown Started') | (MainEvents['Holiday name']=='Lockdown started')|(MainEvents['Holiday name']=='Lockdown Ended')]

         province       date      Holiday name
42        Ontario 2020-03-31  Lockdown Started
43        Ontario 2020-07-28    Lockdown Ended
44        Ontario 2020-10-10  Lockdown Started
45        Ontario 2021-08-02    Lockdown Ended
46        Ontario 2021-03-04  Lockdown Started
47             BC 2020-03-20  Lockdown Started
48             BC 2020-05-19    Lockdown Ended
49             BC 2020-07-11  Lockdown Started
50             BC 2021-08-01    Lockdown Ended
51             BC 2021-03-31  Lockdown Started
52       Manitoba 2020-01-04  Lockdown Started
53       Manitoba 2020-01-06    Lockdown Ended
54       Manitoba 2020-10-30  Lockdown Started
55       Manitoba 2021-12-02    Lockdown Ended
56  New Brunswick 2020-03-19  Lockdown Started
57  New Brunswick 2020-03-07    Lockdown Ended
58  New Brunswick 2020-11-24  Lockdown Started
59  New Brunswick 2021-04-01    Lockdown Ended
60  New Brunswick 2021-03-19  Lockdown Started
61             NL 2020-03-23  Lockdown Started
62             NL 2020-11-05    Lockdown Ended
63             NL 2021-12-02  Lockdown Started
64             NL 2021-03-27    Lockdown Ended
65    Nova Scotia 2020-03-23  Lockdown Started
66    Nova Scotia 2020-01-05    Lockdown Ended
67    Nova Scotia 2020-11-26  Lockdown Started
68    Nova Scotia 2021-04-01    Lockdown Ended
69    Nova Scotia 2021-04-28  Lockdown Started
70        Nunavut 2020-03-17  Lockdown Started
71        Nunavut 2020-01-06    Lockdown Ended
72        Nunavut 2020-06-11  Lockdown Started
73        Nunavut 2020-02-12    Lockdown Ended
74        Nunavut 2021-04-15  Lockdown Started
75            NWT 2020-03-16  Lockdown Started
76            NWT 2020-05-15    Lockdown Ended
77            PEI 2020-03-17  Lockdown Started
78            PEI 2020-05-15    Lockdown Ended
79            PEI 2020-07-12  Lockdown Started
80            PEI 2021-06-01    Lockdown Ended
81         Quebec 2020-03-16  Lockdown Started
82         Quebec 2020-05-20    Lockdown Ended
83         Quebec 2020-01-10  Lockdown Started
84         Quebec 2021-11-01    Lockdown Ended
85        Alberta 2020-03-27  Lockdown Started
86        Alberta 2020-05-14    Lockdown Ended
87        Alberta 2020-11-27  Lockdown Started
88        Alberta 2021-08-02    Lockdown Ended
89        Alberta 2021-09-04  Lockdown Started
90   Saskatchewan 2020-03-18  Lockdown Started
91   Saskatchewan 2020-05-19    Lockdown Ended
92          Yukon 2020-03-18  Lockdown Started
93          Yukon 2020-05-29    Lockdown Ended

In [67]:
MainEvents['Holiday name']=MainEvents['Holiday name'].replace('Lockdown started','Lockdown Started')

In [68]:
MainEvents['Holiday name'].isnull().sum()

0

In [69]:
MainEvents.head()

  province       date                Holiday name
0  Ontario 2020-07-01  Raised Awarness on Airport
1       BC 2020-07-01  Raised Awarness on Airport
2   Quebec 2020-07-01  Raised Awarness on Airport
3  Ontario 2020-11-03  COVID 19 Pandemic declared
4       BC 2020-11-03  COVID 19 Pandemic declared

In [70]:
MainEvents['Holiday name'].unique()

array(['Raised Awarness on Airport', 'COVID 19 Pandemic declared',
       'US border Closed', 'Social Distancing + Mask Mandatory',
       'Lockdown Started', 'Lockdown Ended'], dtype=object)

In [71]:
Lockdown=MainEvents.loc[(MainEvents['Holiday name']=='Lockdown Started')|(MainEvents['Holiday name']=='Lockdown Ended')]

In [72]:
Lockdown

         province       date      Holiday name
42        Ontario 2020-03-31  Lockdown Started
43        Ontario 2020-07-28    Lockdown Ended
44        Ontario 2020-10-10  Lockdown Started
45        Ontario 2021-08-02    Lockdown Ended
46        Ontario 2021-03-04  Lockdown Started
47             BC 2020-03-20  Lockdown Started
48             BC 2020-05-19    Lockdown Ended
49             BC 2020-07-11  Lockdown Started
50             BC 2021-08-01    Lockdown Ended
51             BC 2021-03-31  Lockdown Started
52       Manitoba 2020-01-04  Lockdown Started
53       Manitoba 2020-01-06    Lockdown Ended
54       Manitoba 2020-10-30  Lockdown Started
55       Manitoba 2021-12-02    Lockdown Ended
56  New Brunswick 2020-03-19  Lockdown Started
57  New Brunswick 2020-03-07    Lockdown Ended
58  New Brunswick 2020-11-24  Lockdown Started
59  New Brunswick 2021-04-01    Lockdown Ended
60  New Brunswick 2021-03-19  Lockdown Started
61             NL 2020-03-23  Lockdown Started
62             NL 2020-11-05    Lockdown Ended
63             NL 2021-12-02  Lockdown Started
64             NL 2021-03-27    Lockdown Ended
65    Nova Scotia 2020-03-23  Lockdown Started
66    Nova Scotia 2020-01-05    Lockdown Ended
67    Nova Scotia 2020-11-26  Lockdown Started
68    Nova Scotia 2021-04-01    Lockdown Ended
69    Nova Scotia 2021-04-28  Lockdown Started
70        Nunavut 2020-03-17  Lockdown Started
71        Nunavut 2020-01-06    Lockdown Ended
72        Nunavut 2020-06-11  Lockdown Started
73        Nunavut 2020-02-12    Lockdown Ended
74        Nunavut 2021-04-15  Lockdown Started
75            NWT 2020-03-16  Lockdown Started
76            NWT 2020-05-15    Lockdown Ended
77            PEI 2020-03-17  Lockdown Started
78            PEI 2020-05-15    Lockdown Ended
79            PEI 2020-07-12  Lockdown Started
80            PEI 2021-06-01    Lockdown Ended
81         Quebec 2020-03-16  Lockdown Started
82         Quebec 2020-05-20    Lockdown Ended
83         Quebec 2020-01-10  Lockdown Started
84         Quebec 2021-11-01    Lockdown Ended
85        Alberta 2020-03-27  Lockdown Started
86        Alberta 2020-05-14    Lockdown Ended
87        Alberta 2020-11-27  Lockdown Started
88        Alberta 2021-08-02    Lockdown Ended
89        Alberta 2021-09-04  Lockdown Started
90   Saskatchewan 2020-03-18  Lockdown Started
91   Saskatchewan 2020-05-19    Lockdown Ended
92          Yukon 2020-03-18  Lockdown Started
93          Yukon 2020-05-29    Lockdown Ended

In [73]:
Lockdown.shape

(52, 3)

In [74]:
NL_Lockdown=[['2020-03-23','2020-11-05'],['2021-02-12','2021-03-27']]
date='2021-03-01'

for period in NL_Lockdown:
    print (period)
    
    if date>= period[0] and date <= period[1]:
        print('Lockdown')

['2020-03-23', '2020-11-05']
['2021-02-12', '2021-03-27']
Lockdown

In [75]:
Data.head()

,province,Abbreviation,DailyTotals,date,TotalCases,TotalRecovered,DailyRecovered,TotalDeaths,DailyDeaths,TotalActive,...,Labours Day,Louis Riel Day,Mothers Day,New Year's day,Remembrance Day,St. Jean Baptiste Day,St. Patricks Day,Thanksgiving,Valentine's day,Victoria Day
0,Alberta,AB,0,2020-01-25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,NWT,NT,0,2020-01-25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Yukon,YT,0,2020-01-25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Saskatchewan,SK,0,2020-01-25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,PEI,PE,0,2020-01-25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [76]:
Lockdown.head()

   province       date      Holiday name
42  Ontario 2020-03-31  Lockdown Started
43  Ontario 2020-07-28    Lockdown Ended
44  Ontario 2020-10-10  Lockdown Started
45  Ontario 2021-08-02    Lockdown Ended
46  Ontario 2021-03-04  Lockdown Started

In [77]:
Lockdown['date'].dtype

dtype('<M8[ns]')

In [78]:
import datetime

In [79]:
from datetime import date

In [80]:
print (date.today())

2021-07-16

In [81]:
Today=date.today()

In [82]:
Lockdown['date']=pd.to_datetime(Lockdown['date'])

<ipython-input-82-844a5746bf51>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Lockdown['date']=pd.to_datetime(Lockdown['date'])

In [83]:
Lockdown['date'].dtype

dtype('<M8[ns]')

In [84]:
Lockdown['date']=Lockdown['date'].dt.date

<ipython-input-84-5a75d95305d8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Lockdown['date']=Lockdown['date'].dt.date

In [85]:
A=Lockdown.loc[(Lockdown['date']>Today)]

In [86]:
Lockdown['date'].dtype

dtype('O')

In [87]:
A

    province        date      Holiday name
45   Ontario  2021-08-02    Lockdown Ended
50        BC  2021-08-01    Lockdown Ended
55  Manitoba  2021-12-02    Lockdown Ended
63        NL  2021-12-02  Lockdown Started
84    Quebec  2021-11-01    Lockdown Ended
88   Alberta  2021-08-02    Lockdown Ended
89   Alberta  2021-09-04  Lockdown Started

In [88]:
A['year']=A['date'].apply(lambda x: str(x).split('-')[0])

<ipython-input-88-932e46cea2b3>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A['year']=A['date'].apply(lambda x: str(x).split('-')[0])

In [89]:
A

    province        date      Holiday name  year
45   Ontario  2021-08-02    Lockdown Ended  2021
50        BC  2021-08-01    Lockdown Ended  2021
55  Manitoba  2021-12-02    Lockdown Ended  2021
63        NL  2021-12-02  Lockdown Started  2021
84    Quebec  2021-11-01    Lockdown Ended  2021
88   Alberta  2021-08-02    Lockdown Ended  2021
89   Alberta  2021-09-04  Lockdown Started  2021

In [90]:
A['Date']=A['date'].apply(lambda x: str(x).split('-')[1])

<ipython-input-90-7f51e09da302>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A['Date']=A['date'].apply(lambda x: str(x).split('-')[1])

In [91]:
A['Month']=A['date'].apply(lambda x: str(x).split('-')[2])

<ipython-input-91-416f734d8a31>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A['Month']=A['date'].apply(lambda x: str(x).split('-')[2])

In [92]:
A

    province        date      Holiday name  year Date Month
45   Ontario  2021-08-02    Lockdown Ended  2021   08    02
50        BC  2021-08-01    Lockdown Ended  2021   08    01
55  Manitoba  2021-12-02    Lockdown Ended  2021   12    02
63        NL  2021-12-02  Lockdown Started  2021   12    02
84    Quebec  2021-11-01    Lockdown Ended  2021   11    01
88   Alberta  2021-08-02    Lockdown Ended  2021   08    02
89   Alberta  2021-09-04  Lockdown Started  2021   09    04

In [93]:
A['new_date']=A.apply(lambda row: row['year']+'-'+row['Month']+'-'+row['Date'], axis=1)

<ipython-input-93-1071b401a8c5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A['new_date']=A.apply(lambda row: row['year']+'-'+row['Month']+'-'+row['Date'], axis=1)

In [94]:
A

    province        date      Holiday name  year Date Month    new_date
45   Ontario  2021-08-02    Lockdown Ended  2021   08    02  2021-02-08
50        BC  2021-08-01    Lockdown Ended  2021   08    01  2021-01-08
55  Manitoba  2021-12-02    Lockdown Ended  2021   12    02  2021-02-12
63        NL  2021-12-02  Lockdown Started  2021   12    02  2021-02-12
84    Quebec  2021-11-01    Lockdown Ended  2021   11    01  2021-01-11
88   Alberta  2021-08-02    Lockdown Ended  2021   08    02  2021-02-08
89   Alberta  2021-09-04  Lockdown Started  2021   09    04  2021-04-09

In [95]:
A['new_date2']=A['year']+'-'+A['Month']+"-"+A['Date']

<ipython-input-95-ef14fecb69ee>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  A['new_date2']=A['year']+'-'+A['Month']+"-"+A['Date']

In [96]:
A

,province,date,Holiday name,year,Date,Month,new_date,new_date2
45,Ontario,2021-08-02,Lockdown Ended,2021,08,02,2021-02-08,2021-02-08
50,BC,2021-08-01,Lockdown Ended,2021,08,01,2021-01-08,2021-01-08
55,Manitoba,2021-12-02,Lockdown Ended,2021,12,02,2021-02-12,2021-02-12
63,NL,2021-12-02,Lockdown Started,2021,12,02,2021-02-12,2021-02-12
84,Quebec,2021-11-01,Lockdown Ended,2021,11,01,2021-01-11,2021-01-11
88,Alberta,2021-08-02,Lockdown Ended,2021,08,02,2021-02-08,2021-02-08
89,Alberta,2021-09-04,Lockdown Started,2021,09,04,2021-04-09,2021-04-09

In [97]:
def replace_date(row,Today):
    print(122)
    print(row['date'])
    print(222)
    if (row['date'])>Today:
        l=str(row['date']).split('-')
        year=l[0]
        date=l[1]
        month=l[2]
        return year+'-'+month+'-'+date
Lockdown['new_date']=Lockdown.apply(replace_date,Today=date.today(),axis=1)

122
2020-03-31
222
122
2020-07-28
222
122
2020-10-10
222
122
2021-08-02
222
122
2021-03-04
222
122
2020-03-20
222
122
2020-05-19
222
122
2020-07-11
222
122
2021-08-01
222
122
2021-03-31
222
122
2020-01-04
222
122
2020-01-06
222
122
2020-10-30
222
122
2021-12-02
222
122
2020-03-19
222
122
2020-03-07
222
122
2020-11-24
222
122
2021-04-01
222
122
2021-03-19
222
122
2020-03-23
222
122
2020-11-05
222
122
2021-12-02
222
122
2021-03-27
222
122
2020-03-23
222
122
2020-01-05
222
122
2020-11-26
222
122
2021-04-01
222
122
2021-04-28
222
122
2020-03-17
222
122
2020-01-06
222
122
2020-06-11
222
122
2020-02-12
222
122
2021-04-15
222
122
2020-03-16
222
122
2020-05-15
222
122
2020-03-17
222
122
2020-05-15
222
122
2020-07-12
222
122
2021-06-01
222
122
2020-03-16
222
122
2020-05-20
222
122
2020-01-10
222
122
2021-11-01
222
122
2020-03-27
222
122
2020-05-14
222
122
2020-11-27
222
122
2021-08-02
222
122
2021-09-04
222
122
2020-03-18
222
122
2020-05-19
222
122
2020-03-18
222
122
2020-05-29
222

<ipython-input-97-9efacabac396>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Lockdown['new_date']=Lockdown.apply(replace_date,Today=date.today(),axis=1)

In [98]:
print(date.today())

2021-07-16

In [99]:
Lockdown.head()

   province        date      Holiday name    new_date
42  Ontario  2020-03-31  Lockdown Started        None
43  Ontario  2020-07-28    Lockdown Ended        None
44  Ontario  2020-10-10  Lockdown Started        None
45  Ontario  2021-08-02    Lockdown Ended  2021-02-08
46  Ontario  2021-03-04  Lockdown Started        None

In [100]:
Lockdown['new_date'].replace(to_replace=[None], value=np.nan, inplace=True)

/Users/sahrarahim/opt/anaconda3/lib/python3.8/site-packages/pandas/core/series.py:4509: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

In [101]:
Lockdown.head()

   province        date      Holiday name    new_date
42  Ontario  2020-03-31  Lockdown Started         NaN
43  Ontario  2020-07-28    Lockdown Ended         NaN
44  Ontario  2020-10-10  Lockdown Started         NaN
45  Ontario  2021-08-02    Lockdown Ended  2021-02-08
46  Ontario  2021-03-04  Lockdown Started         NaN

In [102]:
#replace dates
Lockdown['date'] = np.where(~Lockdown['new_date'].isnull(),Lockdown['new_date'],Lockdown['date'])

<ipython-input-102-cfbda63c53d5>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Lockdown['date'] = np.where(~Lockdown['new_date'].isnull(),Lockdown['new_date'],Lockdown['date'])

In [103]:
Lockdown.head()

   province        date      Holiday name    new_date
42  Ontario  2020-03-31  Lockdown Started         NaN
43  Ontario  2020-07-28    Lockdown Ended         NaN
44  Ontario  2020-10-10  Lockdown Started         NaN
45  Ontario  2021-02-08    Lockdown Ended  2021-02-08
46  Ontario  2021-03-04  Lockdown Started         NaN

In [104]:
Lockdown.drop('new_date', axis=1, inplace=True)

/Users/sahrarahim/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [105]:
Lockdown.head()

   province        date      Holiday name
42  Ontario  2020-03-31  Lockdown Started
43  Ontario  2020-07-28    Lockdown Ended
44  Ontario  2020-10-10  Lockdown Started
45  Ontario  2021-02-08    Lockdown Ended
46  Ontario  2021-03-04  Lockdown Started

In [106]:
#Sorting by date
Lockdown_sorted= Lockdown.sort_values(by=['province','date'])
#But If I Sort, how can I make sure that province are not mixed up...

In [107]:
Lockdown_sorted

         province        date      Holiday name
85        Alberta  2020-03-27  Lockdown Started
86        Alberta  2020-05-14    Lockdown Ended
87        Alberta  2020-11-27  Lockdown Started
88        Alberta  2021-02-08    Lockdown Ended
89        Alberta  2021-04-09  Lockdown Started
47             BC  2020-03-20  Lockdown Started
48             BC  2020-05-19    Lockdown Ended
49             BC  2020-07-11  Lockdown Started
50             BC  2021-01-08    Lockdown Ended
51             BC  2021-03-31  Lockdown Started
52       Manitoba  2020-01-04  Lockdown Started
53       Manitoba  2020-01-06    Lockdown Ended
54       Manitoba  2020-10-30  Lockdown Started
55       Manitoba  2021-02-12    Lockdown Ended
61             NL  2020-03-23  Lockdown Started
62             NL  2020-11-05    Lockdown Ended
63             NL  2021-02-12  Lockdown Started
64             NL  2021-03-27    Lockdown Ended
75            NWT  2020-03-16  Lockdown Started
76            NWT  2020-05-15    Lockdown Ended
57  New Brunswick  2020-03-07    Lockdown Ended
56  New Brunswick  2020-03-19  Lockdown Started
58  New Brunswick  2020-11-24  Lockdown Started
60  New Brunswick  2021-03-19  Lockdown Started
59  New Brunswick  2021-04-01    Lockdown Ended
66    Nova Scotia  2020-01-05    Lockdown Ended
65    Nova Scotia  2020-03-23  Lockdown Started
67    Nova Scotia  2020-11-26  Lockdown Started
68    Nova Scotia  2021-04-01    Lockdown Ended
69    Nova Scotia  2021-04-28  Lockdown Started
71        Nunavut  2020-01-06    Lockdown Ended
73        Nunavut  2020-02-12    Lockdown Ended
70        Nunavut  2020-03-17  Lockdown Started
72        Nunavut  2020-06-11  Lockdown Started
74        Nunavut  2021-04-15  Lockdown Started
42        Ontario  2020-03-31  Lockdown Started
43        Ontario  2020-07-28    Lockdown Ended
44        Ontario  2020-10-10  Lockdown Started
45        Ontario  2021-02-08    Lockdown Ended
46        Ontario  2021-03-04  Lockdown Started
77            PEI  2020-03-17  Lockdown Started
78            PEI  2020-05-15    Lockdown Ended
79            PEI  2020-07-12  Lockdown Started
80            PEI  2021-06-01    Lockdown Ended
83         Quebec  2020-01-10  Lockdown Started
81         Quebec  2020-03-16  Lockdown Started
82         Quebec  2020-05-20    Lockdown Ended
84         Quebec  2021-01-11    Lockdown Ended
90   Saskatchewan  2020-03-18  Lockdown Started
91   Saskatchewan  2020-05-19    Lockdown Ended
92          Yukon  2020-03-18  Lockdown Started
93          Yukon  2020-05-29    Lockdown Ended

In [108]:
Lockdown['date'].dtype

dtype('O')

In [109]:
Lockdown['date']=pd.to_datetime(Lockdown['date'])

<ipython-input-109-844a5746bf51>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Lockdown['date']=pd.to_datetime(Lockdown['date'])

In [110]:
Today=date.today()
Today=pd.to_datetime(Today)

In [111]:
def making_pairs(block):
    import copy
#print (Lockdown.index)
    block=block.reset_index(drop=True)
    Period=[]
    temp=[]
    for i in range(block.shape[0]):
        if block.loc[i,'Holiday name']=='Lockdown Started':
            temp.append(block.loc[i,'date'])
        else:
            temp.append(block.loc[i,'date'])
            print (temp)
                
    #for i in temp:
            Period.append(copy.deepcopy(temp))
            temp[::]=[]

        #print (i) 
        #print (Lockdown.loc[i])
    
    #print (block)
    #return 0
    if len(temp)!=0:
        temp.append(Today)
        Period.append(copy.deepcopy(temp))
        temp[::]=[]
        
    return Period
Lockdown_new=Lockdown.groupby(by='province').apply(making_pairs)

[Timestamp('2020-03-27 00:00:00'), Timestamp('2020-05-14 00:00:00')]
[Timestamp('2020-11-27 00:00:00'), Timestamp('2021-02-08 00:00:00')]
[Timestamp('2020-03-20 00:00:00'), Timestamp('2020-05-19 00:00:00')]
[Timestamp('2020-07-11 00:00:00'), Timestamp('2021-01-08 00:00:00')]
[Timestamp('2020-01-04 00:00:00'), Timestamp('2020-01-06 00:00:00')]
[Timestamp('2020-10-30 00:00:00'), Timestamp('2021-02-12 00:00:00')]
[Timestamp('2020-03-23 00:00:00'), Timestamp('2020-11-05 00:00:00')]
[Timestamp('2021-02-12 00:00:00'), Timestamp('2021-03-27 00:00:00')]
[Timestamp('2020-03-16 00:00:00'), Timestamp('2020-05-15 00:00:00')]
[Timestamp('2020-03-19 00:00:00'), Timestamp('2020-03-07 00:00:00')]
[Timestamp('2020-11-24 00:00:00'), Timestamp('2021-04-01 00:00:00')]
[Timestamp('2020-03-23 00:00:00'), Timestamp('2020-01-05 00:00:00')]
[Timestamp('2020-11-26 00:00:00'), Timestamp('2021-04-01 00:00:00')]
[Timestamp('2020-03-17 00:00:00'), Timestamp('2020-01-06 00:00:00')]
[Timestamp('2020-06-11 00:00:00'), Timestamp('2020-02-12 00:00:00')]
[Timestamp('2020-03-31 00:00:00'), Timestamp('2020-07-28 00:00:00')]
[Timestamp('2020-10-10 00:00:00'), Timestamp('2021-02-08 00:00:00')]
[Timestamp('2020-03-17 00:00:00'), Timestamp('2020-05-15 00:00:00')]
[Timestamp('2020-07-12 00:00:00'), Timestamp('2021-06-01 00:00:00')]
[Timestamp('2020-03-16 00:00:00'), Timestamp('2020-05-20 00:00:00')]
[Timestamp('2020-01-10 00:00:00'), Timestamp('2021-01-11 00:00:00')]
[Timestamp('2020-03-18 00:00:00'), Timestamp('2020-05-19 00:00:00')]
[Timestamp('2020-03-18 00:00:00'), Timestamp('2020-05-29 00:00:00')]

In [112]:
Lockdown_new

province
Alberta          [[2020-03-27 00:00:00, 2020-05-14 00:00:00], [...
BC               [[2020-03-20 00:00:00, 2020-05-19 00:00:00], [...
Manitoba         [[2020-01-04 00:00:00, 2020-01-06 00:00:00], [...
NL               [[2020-03-23 00:00:00, 2020-11-05 00:00:00], [...
NWT                   [[2020-03-16 00:00:00, 2020-05-15 00:00:00]]
New Brunswick    [[2020-03-19 00:00:00, 2020-03-07 00:00:00], [...
Nova Scotia      [[2020-03-23 00:00:00, 2020-01-05 00:00:00], [...
Nunavut          [[2020-03-17 00:00:00, 2020-01-06 00:00:00], [...
Ontario          [[2020-03-31 00:00:00, 2020-07-28 00:00:00], [...
PEI              [[2020-03-17 00:00:00, 2020-05-15 00:00:00], [...
Quebec           [[2020-03-16 00:00:00, 2020-05-20 00:00:00], [...
Saskatchewan          [[2020-03-18 00:00:00, 2020-05-19 00:00:00]]
Yukon                 [[2020-03-18 00:00:00, 2020-05-29 00:00:00]]
dtype: object

In [113]:
Lockdown_new['Alberta']

[[Timestamp('2020-03-27 00:00:00'), Timestamp('2020-05-14 00:00:00')],
 [Timestamp('2020-11-27 00:00:00'), Timestamp('2021-02-08 00:00:00')],
 [Timestamp('2021-04-09 00:00:00'), Timestamp('2021-07-16 00:00:00')]]

In [114]:
#pairs=[(i,j)

#for i in Lockdown['date'] if Lockdown['Holiday name']=='Lockdown Started' and i<j for j in Lockdown['date'] if Lockdown['Holiday name']=='Lockdown Ended' and i <j]
#pairs

In [115]:
import copy
print (Lockdown.index)
Lockdown=Lockdown.reset_index(drop=True)
Period=[]
temp=[]
for i in range (Lockdown.shape[0]):
    if Lockdown.loc[i,'Holiday name']=='Lockdown Started':
        temp.append(Lockdown.loc[i,'date'])
    else:
        temp.append(Lockdown.loc[i,'date'])
        print (temp)
    #for i in temp:
        Period.append(copy.deepcopy(temp))
        temp[::]=[]

        #print (i) 
        #print (Lockdown.loc[i])

Int64Index([42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58,
            59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
            76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92,
            93],
           dtype='int64')
[Timestamp('2020-03-31 00:00:00'), Timestamp('2020-07-28 00:00:00')]
[Timestamp('2020-10-10 00:00:00'), Timestamp('2021-02-08 00:00:00')]
[Timestamp('2021-03-04 00:00:00'), Timestamp('2020-03-20 00:00:00'), Timestamp('2020-05-19 00:00:00')]
[Timestamp('2020-07-11 00:00:00'), Timestamp('2021-01-08 00:00:00')]
[Timestamp('2021-03-31 00:00:00'), Timestamp('2020-01-04 00:00:00'), Timestamp('2020-01-06 00:00:00')]
[Timestamp('2020-10-30 00:00:00'), Timestamp('2021-02-12 00:00:00')]
[Timestamp('2020-03-19 00:00:00'), Timestamp('2020-03-07 00:00:00')]
[Timestamp('2020-11-24 00:00:00'), Timestamp('2021-04-01 00:00:00')]
[Timestamp('2021-03-19 00:00:00'), Timestamp('2020-03-23 00:00:00'), Timestamp('2020-11-05 00:00:00')]
[Timestamp('2021-02-12 00:00:00'), Timestamp('2021-03-27 00:00:00')]
[Timestamp('2020-03-23 00:00:00'), Timestamp('2020-01-05 00:00:00')]
[Timestamp('2020-11-26 00:00:00'), Timestamp('2021-04-01 00:00:00')]
[Timestamp('2021-04-28 00:00:00'), Timestamp('2020-03-17 00:00:00'), Timestamp('2020-01-06 00:00:00')]
[Timestamp('2020-06-11 00:00:00'), Timestamp('2020-02-12 00:00:00')]
[Timestamp('2021-04-15 00:00:00'), Timestamp('2020-03-16 00:00:00'), Timestamp('2020-05-15 00:00:00')]
[Timestamp('2020-03-17 00:00:00'), Timestamp('2020-05-15 00:00:00')]
[Timestamp('2020-07-12 00:00:00'), Timestamp('2021-06-01 00:00:00')]
[Timestamp('2020-03-16 00:00:00'), Timestamp('2020-05-20 00:00:00')]
[Timestamp('2020-01-10 00:00:00'), Timestamp('2021-01-11 00:00:00')]
[Timestamp('2020-03-27 00:00:00'), Timestamp('2020-05-14 00:00:00')]
[Timestamp('2020-11-27 00:00:00'), Timestamp('2021-02-08 00:00:00')]
[Timestamp('2021-04-09 00:00:00'), Timestamp('2020-03-18 00:00:00'), Timestamp('2020-05-19 00:00:00')]
[Timestamp('2020-03-18 00:00:00'), Timestamp('2020-05-29 00:00:00')]

In [116]:
print(Period)

[[Timestamp('2020-03-31 00:00:00'), Timestamp('2020-07-28 00:00:00')], [Timestamp('2020-10-10 00:00:00'), Timestamp('2021-02-08 00:00:00')], [Timestamp('2021-03-04 00:00:00'), Timestamp('2020-03-20 00:00:00'), Timestamp('2020-05-19 00:00:00')], [Timestamp('2020-07-11 00:00:00'), Timestamp('2021-01-08 00:00:00')], [Timestamp('2021-03-31 00:00:00'), Timestamp('2020-01-04 00:00:00'), Timestamp('2020-01-06 00:00:00')], [Timestamp('2020-10-30 00:00:00'), Timestamp('2021-02-12 00:00:00')], [Timestamp('2020-03-19 00:00:00'), Timestamp('2020-03-07 00:00:00')], [Timestamp('2020-11-24 00:00:00'), Timestamp('2021-04-01 00:00:00')], [Timestamp('2021-03-19 00:00:00'), Timestamp('2020-03-23 00:00:00'), Timestamp('2020-11-05 00:00:00')], [Timestamp('2021-02-12 00:00:00'), Timestamp('2021-03-27 00:00:00')], [Timestamp('2020-03-23 00:00:00'), Timestamp('2020-01-05 00:00:00')], [Timestamp('2020-11-26 00:00:00'), Timestamp('2021-04-01 00:00:00')], [Timestamp('2021-04-28 00:00:00'), Timestamp('2020-03-17 00:00:00'), Timestamp('2020-01-06 00:00:00')], [Timestamp('2020-06-11 00:00:00'), Timestamp('2020-02-12 00:00:00')], [Timestamp('2021-04-15 00:00:00'), Timestamp('2020-03-16 00:00:00'), Timestamp('2020-05-15 00:00:00')], [Timestamp('2020-03-17 00:00:00'), Timestamp('2020-05-15 00:00:00')], [Timestamp('2020-07-12 00:00:00'), Timestamp('2021-06-01 00:00:00')], [Timestamp('2020-03-16 00:00:00'), Timestamp('2020-05-20 00:00:00')], [Timestamp('2020-01-10 00:00:00'), Timestamp('2021-01-11 00:00:00')], [Timestamp('2020-03-27 00:00:00'), Timestamp('2020-05-14 00:00:00')], [Timestamp('2020-11-27 00:00:00'), Timestamp('2021-02-08 00:00:00')], [Timestamp('2021-04-09 00:00:00'), Timestamp('2020-03-18 00:00:00'), Timestamp('2020-05-19 00:00:00')], [Timestamp('2020-03-18 00:00:00'), Timestamp('2020-05-29 00:00:00')]]

In [117]:
#Make pairs
#result = [(i, j) for i in Lockdown['date'] for j in Lockdown['date'] if i < j]

In [118]:
#result

In [119]:
#Check lockdown for each row.
#for result in Lockdown['date']:
    #if Lockdown['date']>= result[0] and Lockdown['date'] <= result[1]:
        #print('Lockdown')

In [120]:
Lockdown

         province       date      Holiday name
0         Ontario 2020-03-31  Lockdown Started
1         Ontario 2020-07-28    Lockdown Ended
2         Ontario 2020-10-10  Lockdown Started
3         Ontario 2021-02-08    Lockdown Ended
4         Ontario 2021-03-04  Lockdown Started
5              BC 2020-03-20  Lockdown Started
6              BC 2020-05-19    Lockdown Ended
7              BC 2020-07-11  Lockdown Started
8              BC 2021-01-08    Lockdown Ended
9              BC 2021-03-31  Lockdown Started
10       Manitoba 2020-01-04  Lockdown Started
11       Manitoba 2020-01-06    Lockdown Ended
12       Manitoba 2020-10-30  Lockdown Started
13       Manitoba 2021-02-12    Lockdown Ended
14  New Brunswick 2020-03-19  Lockdown Started
15  New Brunswick 2020-03-07    Lockdown Ended
16  New Brunswick 2020-11-24  Lockdown Started
17  New Brunswick 2021-04-01    Lockdown Ended
18  New Brunswick 2021-03-19  Lockdown Started
19             NL 2020-03-23  Lockdown Started
20             NL 2020-11-05    Lockdown Ended
21             NL 2021-02-12  Lockdown Started
22             NL 2021-03-27    Lockdown Ended
23    Nova Scotia 2020-03-23  Lockdown Started
24    Nova Scotia 2020-01-05    Lockdown Ended
25    Nova Scotia 2020-11-26  Lockdown Started
26    Nova Scotia 2021-04-01    Lockdown Ended
27    Nova Scotia 2021-04-28  Lockdown Started
28        Nunavut 2020-03-17  Lockdown Started
29        Nunavut 2020-01-06    Lockdown Ended
30        Nunavut 2020-06-11  Lockdown Started
31        Nunavut 2020-02-12    Lockdown Ended
32        Nunavut 2021-04-15  Lockdown Started
33            NWT 2020-03-16  Lockdown Started
34            NWT 2020-05-15    Lockdown Ended
35            PEI 2020-03-17  Lockdown Started
36            PEI 2020-05-15    Lockdown Ended
37            PEI 2020-07-12  Lockdown Started
38            PEI 2021-06-01    Lockdown Ended
39         Quebec 2020-03-16  Lockdown Started
40         Quebec 2020-05-20    Lockdown Ended
41         Quebec 2020-01-10  Lockdown Started
42         Quebec 2021-01-11    Lockdown Ended
43        Alberta 2020-03-27  Lockdown Started
44        Alberta 2020-05-14    Lockdown Ended
45        Alberta 2020-11-27  Lockdown Started
46        Alberta 2021-02-08    Lockdown Ended
47        Alberta 2021-04-09  Lockdown Started
48   Saskatchewan 2020-03-18  Lockdown Started
49   Saskatchewan 2020-05-19    Lockdown Ended
50          Yukon 2020-03-18  Lockdown Started
51          Yukon 2020-05-29    Lockdown Ended

In [121]:
Lockdown_new

province
Alberta          [[2020-03-27 00:00:00, 2020-05-14 00:00:00], [...
BC               [[2020-03-20 00:00:00, 2020-05-19 00:00:00], [...
Manitoba         [[2020-01-04 00:00:00, 2020-01-06 00:00:00], [...
NL               [[2020-03-23 00:00:00, 2020-11-05 00:00:00], [...
NWT                   [[2020-03-16 00:00:00, 2020-05-15 00:00:00]]
New Brunswick    [[2020-03-19 00:00:00, 2020-03-07 00:00:00], [...
Nova Scotia      [[2020-03-23 00:00:00, 2020-01-05 00:00:00], [...
Nunavut          [[2020-03-17 00:00:00, 2020-01-06 00:00:00], [...
Ontario          [[2020-03-31 00:00:00, 2020-07-28 00:00:00], [...
PEI              [[2020-03-17 00:00:00, 2020-05-15 00:00:00], [...
Quebec           [[2020-03-16 00:00:00, 2020-05-20 00:00:00], [...
Saskatchewan          [[2020-03-18 00:00:00, 2020-05-19 00:00:00]]
Yukon                 [[2020-03-18 00:00:00, 2020-05-29 00:00:00]]
dtype: object

In [122]:
Lockdown_new=pd.DataFrame({'province':Lockdown_new.index,'Lockdown_period':Lockdown_new.values})

In [123]:
Lockdown_merged=Lockdown.merge(Lockdown_new,on='province')

In [124]:
Lockdown_merged.head()

,province,date,Holiday name,Lockdown_period
0,Ontario,2020-03-31,Lockdown Started,"[[2020-03-31 00:00:00, 2020-07-28 00:00:00], [..."
1,Ontario,2020-07-28,Lockdown Ended,"[[2020-03-31 00:00:00, 2020-07-28 00:00:00], [..."
2,Ontario,2020-10-10,Lockdown Started,"[[2020-03-31 00:00:00, 2020-07-28 00:00:00], [..."
3,Ontario,2021-02-08,Lockdown Ended,"[[2020-03-31 00:00:00, 2020-07-28 00:00:00], [..."
4,Ontario,2021-03-04,Lockdown Started,"[[2020-03-31 00:00:00, 2020-07-28 00:00:00], [..."

In [125]:
Data_merged=Data.merge(Lockdown_new,on='province')

In [126]:
Data.head()

,province,Abbreviation,DailyTotals,date,TotalCases,TotalRecovered,DailyRecovered,TotalDeaths,DailyDeaths,TotalActive,...,Labours Day,Louis Riel Day,Mothers Day,New Year's day,Remembrance Day,St. Jean Baptiste Day,St. Patricks Day,Thanksgiving,Valentine's day,Victoria Day
0,Alberta,AB,0,2020-01-25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,NWT,NT,0,2020-01-25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Yukon,YT,0,2020-01-25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Saskatchewan,SK,0,2020-01-25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,PEI,PE,0,2020-01-25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [127]:
Data_merged.head()

,province,Abbreviation,DailyTotals,date,TotalCases,TotalRecovered,DailyRecovered,TotalDeaths,DailyDeaths,TotalActive,...,Louis Riel Day,Mothers Day,New Year's day,Remembrance Day,St. Jean Baptiste Day,St. Patricks Day,Thanksgiving,Valentine's day,Victoria Day,Lockdown_period
0,Alberta,AB,0,2020-01-25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,"[[2020-03-27 00:00:00, 2020-05-14 00:00:00], [..."
1,Alberta,AB,0,2020-01-26,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,"[[2020-03-27 00:00:00, 2020-05-14 00:00:00], [..."
2,Alberta,AB,0,2020-01-27,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,"[[2020-03-27 00:00:00, 2020-05-14 00:00:00], [..."
3,Alberta,AB,0,2020-01-28,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,"[[2020-03-27 00:00:00, 2020-05-14 00:00:00], [..."
4,Alberta,AB,0,2020-01-29,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,"[[2020-03-27 00:00:00, 2020-05-14 00:00:00], [..."

In [128]:
#Data_merged=Data_merged.apply(lambda row:#

def search_lockdown(row):
    for period in row['Lockdown_period']:
        if (row['date']>=period[0]) & (row['date']<=period[1]):
            return True
        
    return False
Data_merged['Lockdown_yesorno']=Data_merged.apply(search_lockdown,axis=1)

In [129]:
Data_merged['date'].dtype

dtype('<M8[ns]')

In [130]:
Data_merged.head()

,province,Abbreviation,DailyTotals,date,TotalCases,TotalRecovered,DailyRecovered,TotalDeaths,DailyDeaths,TotalActive,...,Mothers Day,New Year's day,Remembrance Day,St. Jean Baptiste Day,St. Patricks Day,Thanksgiving,Valentine's day,Victoria Day,Lockdown_period,Lockdown_yesorno
0,Alberta,AB,0,2020-01-25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,"[[2020-03-27 00:00:00, 2020-05-14 00:00:00], [...",False
1,Alberta,AB,0,2020-01-26,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,"[[2020-03-27 00:00:00, 2020-05-14 00:00:00], [...",False
2,Alberta,AB,0,2020-01-27,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,"[[2020-03-27 00:00:00, 2020-05-14 00:00:00], [...",False
3,Alberta,AB,0,2020-01-28,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,"[[2020-03-27 00:00:00, 2020-05-14 00:00:00], [...",False
4,Alberta,AB,0,2020-01-29,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,"[[2020-03-27 00:00:00, 2020-05-14 00:00:00], [...",False

In [131]:
Data_merged['Lockdown_yesorno'].value_counts()

False    3737
True     2281
Name: Lockdown_yesorno, dtype: int64

In [132]:
Data_merged.shape

(6018, 37)

In [133]:
Data_merged.loc[Data_merged['Lockdown_yesorno']==True]

,province,Abbreviation,DailyTotals,date,TotalCases,TotalRecovered,DailyRecovered,TotalDeaths,DailyDeaths,TotalActive,...,Mothers Day,New Year's day,Remembrance Day,St. Jean Baptiste Day,St. Patricks Day,Thanksgiving,Valentine's day,Victoria Day,Lockdown_period,Lockdown_yesorno
62,Alberta,AB,56,2020-03-27,542,33,6,2,0,507,...,0,0,0,0,0,0,0,0,"[[2020-03-27 00:00:00, 2020-05-14 00:00:00], [...",True
63,Alberta,AB,79,2020-03-28,621,53,20,2,0,566,...,0,0,0,0,0,0,0,0,"[[2020-03-27 00:00:00, 2020-05-14 00:00:00], [...",True
64,Alberta,AB,40,2020-03-29,661,73,20,3,1,585,...,0,0,0,0,0,0,0,0,"[[2020-03-27 00:00:00, 2020-05-14 00:00:00], [...",True
65,Alberta,AB,29,2020-03-30,690,94,21,8,5,588,...,0,0,0,0,0,0,0,0,"[[2020-03-27 00:00:00, 2020-05-14 00:00:00], [...",True
66,Alberta,AB,64,2020-03-31,754,120,26,9,1,625,...,0,0,0,0,0,0,0,0,"[[2020-03-27 00:00:00, 2020-05-14 00:00:00], [...",True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5871,Quebec,QC,2519,2021-01-07,220518,186996,2092,8562,74,24955,...,0,0,0,0,0,0,0,0,"[[2020-03-16 00:00:00, 2020-05-20 00:00:00], [...",True
5872,Quebec,QC,2588,2021-01-08,223106,189937,2941,8606,44,24553,...,0,0,0,0,0,0,0,0,"[[2020-03-16 00:00:00, 2020-05-20 00:00:00], [...",True
5873,Quebec,QC,3127,2021-01-09,226233,192979,3042,8647,41,24589,...,0,0,0,0,0,0,0,0,"[[2020-03-16 00:00:00, 2020-05-20 00:00:00], [...",True
5874,Quebec,QC,2588,2021-01-10,228821,195663,2684,8686,39,24454,...,0,0,0,0,0,0,0,0,"[[2020-03-16 00:00:00, 2020-05-20 00:00:00], [...",True
5875,Quebec,QC,1869,2021-01-11,230690,197938,2275,8737,51,23996,...,0,0,0,0,0,0,0,0,"[[2020-03-16 00:00:00, 2020-05-20 00:00:00], [...",True

In [134]:
Data_merged.loc[Data_merged['Lockdown_yesorno']==False]

,province,Abbreviation,DailyTotals,date,TotalCases,TotalRecovered,DailyRecovered,TotalDeaths,DailyDeaths,TotalActive,...,Mothers Day,New Year's day,Remembrance Day,St. Jean Baptiste Day,St. Patricks Day,Thanksgiving,Valentine's day,Victoria Day,Lockdown_period,Lockdown_yesorno
0,Alberta,AB,0,2020-01-25,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,"[[2020-03-27 00:00:00, 2020-05-14 00:00:00], [...",False
1,Alberta,AB,0,2020-01-26,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,"[[2020-03-27 00:00:00, 2020-05-14 00:00:00], [...",False
2,Alberta,AB,0,2020-01-27,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,"[[2020-03-27 00:00:00, 2020-05-14 00:00:00], [...",False
3,Alberta,AB,0,2020-01-28,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,"[[2020-03-27 00:00:00, 2020-05-14 00:00:00], [...",False
4,Alberta,AB,0,2020-01-29,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,"[[2020-03-27 00:00:00, 2020-05-14 00:00:00], [...",False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6013,Quebec,QC,410,2021-05-29,369728,354104,662,11125,7,4499,...,0,0,0,0,0,0,0,0,"[[2020-03-16 00:00:00, 2020-05-20 00:00:00], [...",False
6014,Quebec,QC,315,2021-05-30,370043,354734,630,11127,2,4182,...,0,0,0,0,0,0,0,0,"[[2020-03-16 00:00:00, 2020-05-20 00:00:00], [...",False
6015,Quebec,QC,276,2021-05-31,370319,355266,532,11128,1,3925,...,0,0,0,0,0,0,0,0,"[[2020-03-16 00:00:00, 2020-05-20 00:00:00], [...",False
6016,Quebec,QC,208,2021-06-01,370527,355785,519,11133,5,3609,...,0,0,0,0,0,0,0,0,"[[2020-03-16 00:00:00, 2020-05-20 00:00:00], [...",False
6017,Quebec,QC,288,2021-06-02,370815,356202,417,11138,5,3475,...,0,0,0,0,0,0,0,0,"[[2020-03-16 00:00:00, 2020-05-20 00:00:00], [...",False

In [135]:
#Drop rows not required
data=(Data_merged.drop(['Holiday name'], axis=1))

In [136]:
data.drop(['Abbreviation'], axis=1, inplace=True)

In [137]:
data.drop(['DailyRecovered'], axis=1, inplace=True)

In [138]:
data.drop(['TotalDeaths'], axis=1, inplace=True)

In [139]:
data.drop(['DailyDeaths'], axis=1, inplace=True)

In [140]:
data.drop(['DailyVaccinated'], axis=1, inplace=True)

In [141]:
data=data.drop(['TotalRecovered'], axis=1)

In [142]:
data=data.drop(['Lockdown_period'], axis=1)

In [143]:
data.columns

Index(['province', 'DailyTotals', 'date', 'TotalCases', 'TotalActive',
       'DailyActive', 'TotalVaccinated', 'Aboriginal Day', 'Boxing Day',
       'Canada Day', 'Christmas', 'Civic Holiday', 'Easter', 'Family Day',
       'Fathers Day', 'Halloween', 'Heritage Day', 'Islander Day',
       'Labours Day', 'Louis Riel Day', 'Mothers Day', 'New Year's day',
       'Remembrance Day', 'St. Jean Baptiste Day', 'St. Patricks Day',
       'Thanksgiving', 'Valentine's day', 'Victoria Day', 'Lockdown_yesorno'],
      dtype='object')

In [144]:
#saving the cleaned dataset as .csv file
data.to_csv('provincial_data2.csv')